### ISSUE TITLE
Update image from webui is not working, how to flash new firmware for intel_ast2500 platform??

### ISSUE THREAD

**Issue by tejas-patil20** [Intel-BMC/openbmc#11]
I have built the image for intel_ast2500 with target as intel-platforms , also flashed the same image on Wolfpass server.

Now i am trying to flash different openbmc image but i cant able to do any type of flashing like  web_flash/tftp/socflash/inbuilt_shell flash.

Which firmware image we should upload through web/tftp flash ?? , can anyone tell me the name for that image.

Is there any document available for flashing the firmware???
Can anybody tell me how to flash different/same intel firmware image through any type of flashing ????? 

Waiting for someone's i/ps.

**Comment by kuiyingw** [comment]
Please use the tarball.
