### ISSUE TITLE
CurrentBMCState: BMCState.NotReady [S2600WF]

### ISSUE THREAD

**Issue by akashgj** [Intel-BMC/openbmc#19]
I am using latest OpenBMC firmmware with S2600WF configuration. 

_obmcutil state_ command shows **CurrentBMCState: BMCState.NotReady.**

root@s2600wf:~# obmcutil state
CurrentBMCState     : xyz.openbmc_project.State.BMC.BMCState.NotReady
CurrentPowerState   : xyz.openbmc_project.State.Chassis.PowerState.Off
Error finding '/xyz/openbmc_project/state/host0' service: No such file or directory

root@s2600wf:~# systemctl list-jobs --no-pager
JOB UNIT                                                            TYPE  STATE  
116 obmc-led-group-start@bmc_booted.service                         start waiting
  1 multi-user.target                                               start waiting
 77 phosphor-reset-host-check@0.service                             start waiting
 76 obmc-host-reset@0.target                                        start waiting
 94 mapper-wait@-xyz-openbmc_project-Chassis-Control-Power0.service start running
 96 phosphor-reset-host-running@0.service                           start waiting
 90 op-reset-chassis-running@0.service                              start waiting
 87 obmc-host-reset-running@0.target                                start waiting
 89 op-reset-chassis-on@0.service                                   start waiting
 98 phosphor-reset-sensor-states@0.service                          start waiting
155 xyz.openbmc_project.Time.Manager.service                        start waiting
147 xyz.openbmc_project.State.Host.service                          start waiting
121 phosphor-discover-system-state@0.service                        start waiting
100 mapper-wait@-xyz-openbmc_project-state-host0.service            start running
 92 obmc-power-reset-on@0.target                                    start waiting

**Comment by feistjj** [comment]
Please use this machine: https://github.com/Intel-BMC/openbmc/tree/intel/meta-openbmc-mods/meta-wolfpass/conf

**Comment by akashgj** [comment]
I tried with  _https://github.com/Intel-BMC/openbmc/tree/intel/meta-openbmc-mods/meta-wolfpass/conf_. Still some services are waiting to start. That includes _ipmi-kcs services_. Because of that  _kcsbridged_ daemon is not running.

root@intel-obmc:/usr/bin# systemctl list-jobs --no-pager         
JOB UNIT                                                           TYPE  STATE  
109 mapper-wait@-xyz-openbmc_project-state-host0.service           start running
112 phosphor-ipmi-net@eth1.service                                 start waiting
126 obmc-led-group-start@bmc_booted.service                        start waiting
108 xyz.openbmc_project.Time.Manager.service                       start waiting
 86 mapper-wait@-xyz-op...ontrol-security-restriction_mode.service start running
  1 multi-user.target                                              start waiting
157 phosphor-ipmi-kcs@ipmi_kcs3.service                            start waiting
 85 specialmodemgr.service                                         start waiting
 58 node-manager-proxy.service                                     start waiting
135 phosphor-ipmi-kcs@ipmi_kcs4.service                            start waiting
 77 ipmb.service                                                   start waiting
116 mapper-wait@-xyz-openbmc_project-state-os.service              start running
113 phosphor-ipmi-host.service                                     start waiting
164 phosphor-ipmi-net@eth0.service                                 start waiting

**Comment by lqu** [comment]
I'm having the same problem. https://github.com/openbmc/openbmc/issues/3607

**Comment by lqu** [comment]
Hi @akashgj Are you using commit 35e295e2a161fcf146ea031de53431b2888521fa? I got a build error.
```
dd: failed to open '/xyz/build/tmp/deploy/images/intel-ast2500/fitImage-rootfs-intel-ast2500.bin': No such file or directory
WARNING: exit code 1 from a shell command.
ERROR: Function failed: do_generate_auto (log file is located at /xyz/build/tmp/work/intel_ast2500-openbmc-linux-gnueabi/obmc-phosphor-image/1.0-r0/temp/log.do_generate_auto.29676)

```
