### ISSUE TITLE
SDK support?

### ISSUE THREAD

**Issue by Andywjzhang** [Intel-BMC/openbmc#50]
Dear sirs,

I download Intel openbmc recently, and prepare to do same test with the firmware. I used devtool to get code package and do some modify and debug. But there are so many packages that I can not download all of them one by one. Is there any easy way for me to get all the code packages? Thanks very much.

BR,
Andy

**Comment by cjia4** [comment]
Follow the instruction in README to build the entire platform. Bitbake process will download source code automatically. There is no need to download manually one by one.

**Comment by Andywjzhang** [comment]
Got it, thank you!
