### ISSUE TITLE
Question on wolf pass

### ISSUE THREAD

**Issue by ykniu** [Intel-BMC/openbmc#60]
I’m new to Openbmc. Any feedback is greatly appreciated.
I’m trying a openbmc wolf-pass build for SOL function test.
I found that WP default is using ttyS2 as host UART and ttyS3 as the mirrored UART.
As it defines OBMC_CONSOLE_HOST_TTY = "ttyS2" in obmc-console_%.bbappend And local-tty = ttyS3 in obmc-console/obmc-console.conf.
My question is:
1. why does WP chose these two UARTs? Is it decided by HW board? Can I change it to anything else, say ttyS0&ttyS1?
2. Does this mean that WP host must be connected with the BMC’s ttyS2(UART3) through the LPC bus?
3. Why does obmc-console/obmc-console@.service routes uart4->io1, io1->uart4, uart1->uart3, uart3->uart1? Again, is it decided by HW board?
4. Why does openbmc-console needs a local-tty? Can it be simply removed?

**Comment by cjia4** [comment]
#1 yes, it is decided by HW schematic.  You can not change to others as long as you use WFP. 
#2 yes, and it is eSPI interface (not LPC). 

2021-02-04 

chunhui.jia 



发件人：ykniu <notifications@github.com>
发送时间：2021-02-02 00:35
主题：[Intel-BMC/openbmc] Question on wolf pass (#60)
收件人："Intel-BMC/openbmc"<openbmc@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

I’m new to Openbmc.
I’m trying a openbmc wolf-pass image for SOL function test.
I found that WP default is using ttyS2 as host UART and ttyS3 as the mirrored UART.
As it defines OBMC_CONSOLE_HOST_TTY = "ttyS2" in obmc-console_%.bbappend And local-tty = ttyS3 in obmc-console/obmc-console.conf.
My question is
why does WP chose these two UARTs? Is it decided by HW board? Can I change it to anything else, say ttyS0&ttyS1? 
Does this means that WP host is using the ttyS2(UART3) on the LPC bus to

**Comment by ykniu** [comment]
@cjia4 thanks very much for reply.
