### ISSUE TITLE
Question about thermal mode of WolfPass

### ISSUE THREAD

**Issue by yuweiChangInsyde** [Intel-BMC/openbmc#8]
Hi,

I am looking into fan-control feature of WolfPass these days,
and I got some question about thermal mode setting.

As far as I know, there are two thermal mode settings:
 - "Performance":
      Takes input sensor controller "Front_Panel_LCC", "CPU1" and "CPU2" only,
      so phosphor-pid-control will not control fan speed in this thermal setting.
      (Fan speed will be set in a fix value by set_fan_speeds.py)
      Shouldn't the fan speed be adjusted according to the HOST CPU temperature?

- "Acoustic":
     Takes all sensor controller on dbus, phosphor-pid-control will control
     fan speed according to HOST CPU temperature.

May I know purpose of each "Performance" and "Acoustic" thermal mode settings?

Best regards,
yuwei

**Comment by feistjj** [comment]
These are still under development, and the clamps for each are changing. The purpose of thermal modes are to create a preference for CPU throttling. In performance, acoustic performance is sacrificed for better CPU performance. In acoustic, CPU throttling may happen to not go over an acoustic fan noise limit.

**Comment by yuweiChangInsyde** [comment]
Hello, James

Thanks for the response.
I got it now.

Best regards,
yuwei
